# **Basic Things [Variables, DataTypes, eval()-function, help()]**

In [2]:
# No need to define data type of variables in case of python, like we used to do in other languages

x, y = 10, 1.12
z = 'Single Quotes'
a = "Double Quotes"
b = True
c = "d"
d = 's'
e = int(1.12)

print (type(x), type(y), type(z), type(a), type(b), type(c), type(d), type(e), sep="\n")

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>
<class 'str'>
<class 'str'>
<class 'int'>


In [6]:
# eval() function Evaluates a given argument and gives the output, the argument should be in String

x = eval("10/2+3*2")
print("1)Result =", x)

y = "10+5/2*8"
print("2)Result =",eval(y))


1)Result = 11.0
2)Result = 30.0


In [7]:
# help() function helps you get info on anything you require on python , just type help() in shell, you will be guided accordingly

help()


Welcome to Python 3.10's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the internet at https://docs.python.org/3.10/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".



# **Input and Printing Statements**



In [1]:
#Printing Statements -1
a = "Welcome To KRS Classes ML"
print("Hello Guys!", a)

#Printing Statements -2
b = 143
print("Let us Say : ", end=" ")
print(b, 'is my Number')

#Printing Statements -3
print("Printing Sequence Type-1 = {} --- {}".format("Text_1","Text_2"))

print("Trial:{} {}".format("t1","t2"))

#Printing Statements -4
x = "Text-1"
y = "Text-2"
print(f"Printing Sequence Type-2 = {x} --- {y}")

Hello Guys! Welcome To KRS Classes ML
Let us Say :  143 is my Number
Printing Sequence Type-1 = Text_1 --- Text_2
Trial:t1 t2
Printing Sequence Type-2 = Text-1 --- Text-2


In [ ]:
# By default Input is taken is String format, 
# so if we require input in any other format we need to change its type - by eval() or explicit conversion

a = input("1)Enter Anything : ")
print("Input = ", a, "; Type :", type(a))

b = eval(input("\n2)Enter Any Number : "))
print("Input = ", b, "; Type :", type(b))

1)Enter Anything : 123
Input =  123 ; Type : <class 'str'>

2)Enter Any Number : 11.3
Input =  11.3 ; Type : <class 'float'>


# **Random Function**

In [2]:
# Lets understand by a Dice Game : Lets see what you get
import random as rd
choice = rd.randrange(1,6+1) # range is from 1 to 6
choice2 = rd.randint(1,6) # range is from 1 to 6
choice3 = rd.random() # gives any random number between 0 and 1 in float 
print("Choice 1 :", choice)
print("Choice 2 :", choice2)
print("Choice 3 :", choice3)


Choice 1 : 1
Choice 2 : 5
Choice 3 : 0.9831377329502572


# **Set, List, Tuple, Dictionary**

In [ ]:
# List (Indexing : 0 onwards LHS, -1 onwards RHS)
# Mutable, Different Data types allowed in same list

LIST = ['1', 2, "NAMES", 11, 1.2, 2, 654, 55.3, 'h', 'Hello']
print(LIST)
print(LIST[2:6:2]) # index 2 to 5, jump=2
print(LIST[:4]) # index 0 to 3
print(LIST[6:]) # index 6 to last
print(LIST[-5:-2]) # index reverse -5 to -3

LIST.append("NEW") # adding new element in list
print(LIST)

LIST.pop(3) # deleting element in list by index
print(LIST)

LIST.remove('h') # deleting element in list by item
print(LIST)

NestedList = [[1,2,3],[4,5],['sdfgh']]
print(NestedList)

['1', 2, 'NAMES', 11, 1.2, 2, 654, 55.3, 'h', 'Hello']
['NAMES', 1.2]
['1', 2, 'NAMES', 11]
[654, 55.3, 'h', 'Hello']
[2, 654, 55.3]
['1', 2, 'NAMES', 11, 1.2, 2, 654, 55.3, 'h', 'Hello', 'NEW']
['1', 2, 'NAMES', 1.2, 2, 654, 55.3, 'h', 'Hello', 'NEW']
['1', 2, 'NAMES', 1.2, 2, 654, 55.3, 'Hello', 'NEW']
[[1, 2, 3], [4, 5], ['sdfgh']]


In [ ]:
# Set are represented by { } (values enclosed in curly braces)

var = {"Geeks", "for", "Geeks"}
print(type(var))

# typecasting list to set
myset = set(["a", "b", "c"])
print(myset)

# Adding element to the set
myset.add("d")
print(myset)

print("\n__Next__\n")

# Python program to demonstrate differences
# between normal and frozen set

# Same as {"a", "b","c"}
normal_set = set(["a", "b","c"])

print("Normal Set")
print(normal_set)

# A frozen set
frozen_set = frozenset(["e", "f", "g"])

print("\nFrozen Set")
print(frozen_set) # Uncommenting this line would cause error as we are trying to add element to a frozen set : frozen_set.add("h")

print("\n__Next__\n")




<class 'set'>
{'a', 'b', 'c'}
{'a', 'b', 'd', 'c'}

__Next__

Normal Set
{'a', 'b', 'c'}

Frozen Set
frozenset({'f', 'e', 'g'})


In [ ]:
# Tuple (Indexing : 0 onwards LHS, -1 onwards RHS)
# Imutable, Different Data types allowed in same Tuple

TUP = ('1', 2, "NAMES", 11, 1.2, 2, 654, 55.3, 'h', 'Hello')
print(TUP)
print(TUP[2:4]) # index 2 to 3
print(TUP[:4]) # index 0 to 3
print(TUP[6:]) # index 6 to last
print(TUP[-5:-2]) # index reverse -5 to -3


('1', 2, 'NAMES', 11, 1.2, 2, 654, 55.3, 'h', 'Hello')
('NAMES', 11)
('1', 2, 'NAMES', 11)
(654, 55.3, 'h', 'Hello')
(2, 654, 55.3)


In [1]:
# Dictionary (Key-Value Pair)

Dt = {1:"A", 2:"B", 3:"C"}
print(Dt)

print(Dt.keys()) # get keys

print(Dt[2]) # print value via key
print(Dt.get(3))

Dt.pop(2) # delete key
print(Dt)

Dt.update({2: "NEW"}) # add new key-pair value
print(Dt)

ND = {1:[["Name","age",21011],[1,2,334]],2:[1,3]}
print(ND)

{1: 'A', 2: 'B', 3: 'C'}
dict_keys([1, 2, 3])
B
C
{1: 'A', 3: 'C'}
{1: 'A', 3: 'C', 2: 'NEW'}
{1: [['Name', 'age', 21011], [1, 2, 334]], 2: [1, 3]}


# **Loops in Python**

In [7]:
# for - Loop
LIST = ['1', 2, "NAMES", 11, 1.2, 2, 654, 55.3, 'h', 'Hello']
for i in range(1, 10):
  print(i, end="  ")

print("\n__Next__")

for i in range (1, 10, 2):
  print(i, end="  ")

print("\n__Next__")

for i in LIST:
  print(i, end="  ")

print("\n__Next__")

# for i in TUP:
#   print(i, end="  ")

1  2  3  4  5  6  7  8  9  
__Next__
1  3  5  7  9  
__Next__
1  2  NAMES  11  1.2  2  654  55.3  h  Hello  
__Next__


In [ ]:
# while - Loop

i=1
while (i<=10):
  print(i, end="  ")
  i+=1

print("\n__Next__")

j=1
while(True):
  if(j<=10):
    print(j*2, end="  ")
  elif(j>10 and j<=20):
    print(j*-1, end="  ")
  else:
    break
  j+=1

1  2  3  4  5  6  7  8  9  10  
__Next__
2  4  6  8  10  12  14  16  18  20  -11  -12  -13  -14  -15  -16  -17  -18  -19  -20  

# **File Management** 


In [8]:
# a file named "New", will be opened with the reading mode.
file = open('New.txt', 'r')
# This will print every line one by one in the file
for each in file:
    print (each)

print("\n__Next__")



FileNotFoundError: [Errno 2] No such file or directory: 'New.txt'

In [ ]:
# Python code to illustrate read() mode
file = open("New.txt", "r")
print (file.read())

print("\n__Next__")

abcd
efgh
ijkh
jklm
nop
qrs
tuv

__Next__


In [ ]:
# Python code to create a file
file = open('New2.txt','w')
file.write("This is the write command")
file.write("It allows us to write in a particular file")
file.close()

print("\n__Next__")


__Next__


In [ ]:
# Python code to illustrate split() function
with open("New.txt", "r") as file:
    data = file.readlines()
    for line in data:
        word = line.split()
        print (word)

['abcd']
['efgh']
['ijkh']
['jklm']
['nop']
['qrs']
['tuv']


In [ ]:
# for binary file formats (mostly required for saving and loading trained model file)

import pickle

model = ["Data_1", "Data_2", "Data_3", "Data_4"]

filename = 'File_Binary.train'

pickle.dump(model, open(filename,'wb')) #saving the file in binary file format
loadMODEL = pickle.load(open('File_Binary.train','rb')) #loading the binary file

for i in loadMODEL: #after loading the file printing its contents
  print(i)

Data_1
Data_2
Data_3
Data_4


In [1]:
class Point:
    x=0
    y=0
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __str__(self):
        return("("+str(self.x)+","+str(self.y)+")")

In [4]:
import numpy as np

np.array([1,2,3])
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.arange(200,16,-3)

array([200, 197, 194, 191, 188, 185, 182, 179, 176, 173, 170, 167, 164,
       161, 158, 155, 152, 149, 146, 143, 140, 137, 134, 131, 128, 125,
       122, 119, 116, 113, 110, 107, 104, 101,  98,  95,  92,  89,  86,
        83,  80,  77,  74,  71,  68,  65,  62,  59,  56,  53,  50,  47,
        44,  41,  38,  35,  32,  29,  26,  23,  20,  17])

In [18]:
np.linspace(10,20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [27]:
np.linspace(10,20,10)
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [23]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
np.random.rand(5,2)

array([[0.4473332 , 0.76042342],
       [0.98842009, 0.20040615],
       [0.99857693, 0.26660594],
       [0.10348538, 0.24027047],
       [0.37147943, 0.04516689]])

In [36]:
np.random.randint(0,10,[5,5])

array([[0, 1, 0, 4, 2],
       [8, 5, 8, 9, 9],
       [4, 5, 1, 3, 9],
       [0, 7, 2, 8, 9],
       [5, 4, 3, 7, 1]])

In [37]:
np.random.randint(0,100,[5,5])

array([[17, 16,  7, 87, 22],
       [82, 88, 66, 86, 86],
       [ 6, 86, 16, 82, 72],
       [16, 40, 79, 54, 29],
       [34, 87, 53, 68, 90]])

In [41]:
np.random.randn(2,5)

array([[-1.12419151,  0.79250214,  1.4882538 , -0.29277954,  0.88078613],
       [-1.29036297, -2.23277406, -0.2162475 , -0.05055988, -0.25365748]])

In [43]:
arr = np.random.randn(10)
arr

array([ 1.3039401 ,  0.4359436 , -0.07607384, -0.95516253, -1.68841398,
        0.7222718 , -0.47488416,  0.23871052, -0.20631504,  0.69095058])

In [44]:
arr.shape

(10,)

In [48]:
arr2 = arr.reshape(2,5)
arr2

array([[ 1.3039401 ,  0.4359436 , -0.07607384, -0.95516253, -1.68841398],
       [ 0.7222718 , -0.47488416,  0.23871052, -0.20631504,  0.69095058]])

In [50]:
arr.shape

(10,)

In [53]:
arr2.argmax()

0

In [47]:
arr2.shape

(2, 5)

In [54]:
arr = np.random.randint(0,10,(5,5))
arr

array([[1, 3, 0, 2, 1],
       [7, 8, 1, 1, 6],
       [3, 7, 0, 4, 5],
       [7, 9, 5, 3, 7],
       [7, 7, 5, 1, 4]])

In [55]:
arr[2,2]

0

In [56]:
arr[1:3,0:4]

array([[7, 8, 1, 1],
       [3, 7, 0, 4]])

In [59]:
arr2 = np.random.randint(0,10,10)
arr2

array([4, 8, 4, 1, 8, 7, 1, 5, 0, 0])

In [60]:
arr2[1:4]

array([8, 4, 1])

In [61]:
arr1 = np.random.randint(0,10,10)
arr1

array([0, 3, 1, 6, 0, 6, 0, 2, 1, 2])

In [62]:
arr1+10

array([10, 13, 11, 16, 10, 16, 10, 12, 11, 12])

In [63]:
arr1*2

array([ 0,  6,  2, 12,  0, 12,  0,  4,  2,  4])

In [64]:
np.sqrt(arr1)

array([0.        , 1.73205081, 1.        , 2.44948974, 0.        ,
       2.44948974, 0.        , 1.41421356, 1.        , 1.41421356])

In [65]:
np.sin(arr1)

array([ 0.        ,  0.14112001,  0.84147098, -0.2794155 ,  0.        ,
       -0.2794155 ,  0.        ,  0.90929743,  0.84147098,  0.90929743])

In [66]:
def add(a,b):
    return a+5,b+5
result = add(3,2)
print(result)
#test

(8, 7)
